/*
 * CustomerInfoEditorJDialog.java
 *
 * Created on 2006年12月28日, 上午12:28
 */

package com.ffcs.customerinfomgr.customerinfomgr;

import com.ffcs.customerinfomgr.util.ChangeComboBox;
import com.ffcs.customerinfomgr.util.CheckStringUtil;
import com.ffcs.customerinfomgr.util.ComboxItemCommand;
import com.ffcs.customerinfomgr.util.RestrictText;
import com.ffcs.system.utility.Transform;
import com.ffcs.util.AppContext;
import com.ffcs.util.bo.customerinfomgr.ICustomerInfoMgrFacade;
import com.ffcs.util.bo.customerinfomgr.IRegionInfoMgrFacade;
import com.ffcs.util.bo.customerinfomgr.ITradeClsInfoMgrFacade;
import com.ffcs.util.domain.customerinfomgr.Codetbl;
import com.ffcs.util.domain.customerinfomgr.Customer;
import java.awt.Frame;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import org.openide.util.NbBundle;
import org.openide.windows.WindowManager;

/**
 *
 * @author  ldh
 */
public class CustomerInfoEditorJDialog extends javax.swing.JDialog {
    
    private String task;
    
    private CustomerInfoEditorTopComponent opener;
    
    //用于转换所选项和ID值
    private ComboxItemCommand commandTradeId;
    private ComboxItemCommand commandRegionId;
    private ComboxItemCommand commandCbxCustGrade;
    private ComboxItemCommand commandCbxCustType;
    private ComboxItemCommand commandCbxCreditLevel;
    private ComboxItemCommand commandCbxCustLevel;
    private ComboxItemCommand commandCbxServiceLevel;
    
    //主窗体
    private Frame mainFrame;
    
    //用于暂时存储新增的或要修改的ID号
    private String customerid;
    /**
     * Creates new form CustomerInfoEditorJDialog
     */
    public CustomerInfoEditorJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mainFrame=parent;
        this.setVisible(true);
    }
    public CustomerInfoEditorJDialog(java.awt.Frame parent,
            String task,
            CustomerInfoEditorTopComponent opener,
            Customer customer
            ) {
        super(parent, true);
        this.opener=opener;
        mainFrame=parent;
        initComponents();
        this.task=task;
        chagneTitle(task);
        //使combobox具有查询的功能
        ChangeComboBox ccbx=new ChangeComboBox(cbxParentName);
        iniText(customer);
        this.setLocation(parent.getWidth()/2-this.getWidth()/2
                ,parent.getHeight()/2-this.getHeight()/2);
        restrictInput();
        this.setVisible(true);
    }
    //用于客户菜树菜单的.如果task为"add"时id为行业的id,为"change"时id为客户的id
    public CustomerInfoEditorJDialog(java.awt.Frame parent,
            String task,
            String id
            ) {
        super(parent, true);
        this.opener=null;
        mainFrame=parent;
        initComponents();
        this.task=task;
        chagneTitle(task);
        //使combobox具有查询的功能
        ChangeComboBox ccbx=new ChangeComboBox(cbxParentName);
        Customer customer=new Customer();
        if(task.equals("change")){
            ICustomerInfoMgrFacade mgr=(ICustomerInfoMgrFacade)AppContext.getInstance()
            .getAppContext().getBean("iCustomerInfoMgrFacade");
            customer=mgr.getCustomerInfo(id);
        }else if(task.equals("add")){
            //获得新客户的id
            ICustomerInfoMgrFacade mgr=(ICustomerInfoMgrFacade)AppContext.getInstance()
            .getAppContext().getBean("iCustomerInfoMgrFacade");
            long maxid=Long.parseLong(mgr.getCustomerMaxId())+1;
            customer.setCustomerid(String.valueOf(maxid));
            customer.setTradeclsid(Integer.parseInt(id));
        }
        iniText(customer);
        this.setLocation(parent.getWidth()/2-this.getWidth()/2
                ,parent.getHeight()/2-this.getHeight()/2);
        restrictInput();
        this.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" 生成的代码 ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNameCN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCustCode = new javax.swing.JTextField();
        txtCustAddr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtRemark = new javax.swing.JTextField();
        cbxTradeclsid = new javax.swing.JComboBox();
        cbxRegionID = new javax.swing.JComboBox();
        cbxParentName = new javax.swing.JComboBox();
        cbxCustGrade = new javax.swing.JComboBox();
        cbxCustLevel = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtFileNo = new javax.swing.JTextField();
        txtAbbrewPY = new javax.swing.JTextField();
        txtAbbrewCN = new javax.swing.JTextField();
        txtOldName = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtCounts = new javax.swing.JTextField();
        txtBank = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtLinkName = new javax.swing.JTextField();
        txtLinkPhone = new javax.swing.JTextField();
        txtLinkMobile = new javax.swing.JTextField();
        txtLinkEmail = new javax.swing.JTextField();
        txtLinkFax = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMgrName = new javax.swing.JTextField();
        txtMgrMobile = new javax.swing.JTextField();
        txtMgrPhone = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNameEN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxCreditLevel = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbxCustType = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbxServiceLevel = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("\u5927\u5ba2\u6237\u57fa\u672c\u4fe1\u606f"));
        jLabel2.setText("\u5ba2\u6237\u4e2d\u6587\u540d\u79f0:");

        jLabel3.setText("\u884c\u4e1a:");

        jLabel5.setText("\u5ba2\u6237\u7f16\u7801:");

        jLabel6.setText("\u5ba2\u6237\u5730\u5740:");

        jLabel7.setText("\u5ba2\u6237\u7b49\u7ea7:");

        jLabel8.setText("\u5ba2\u6237\u7ea7\u522b:");

        jLabel12.setText("\u4e0a\u7ea7\u5ba2\u6237:");

        jLabel13.setText("\u5907\u6ce8:");

        jLabel14.setText("\u533a\u57df:");

        cbxTradeclsid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "2", "3", "4" }));

        cbxRegionID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "1", "2", "3", "4", "5", "6" }));

        cbxCustGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCustLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("*");

        jLabel23.setForeground(new java.awt.Color(255, 102, 102));
        jLabel23.setText("*");

        jLabel25.setText("\u5bf9\u5e94\u6587\u4ef6\u53f7:");

        jLabel26.setText("\u4e2d\u6587\u540d\u7f29\u5199:");

        jLabel27.setText("\u62fc\u97f3\u7f29\u5199:");

        jLabel28.setText("\u66fe\u7528\u540d:");

        jLabel29.setText("\u94f6\u884c\u5e10\u53f7:");

        jLabel30.setText("\u6240\u5728\u94f6\u884c:");

        jLabel31.setText("\u8d35\u5bbe\u7f16\u53f7:");

        jLabel24.setForeground(new java.awt.Color(255, 102, 102));
        jLabel24.setText("*");

        jLabel32.setForeground(new java.awt.Color(255, 102, 102));
        jLabel32.setText("*");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(jLabel24))
                    .add(jLabel32, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(2, 2, 2)
                            .add(jLabel26))
                        .add(jLabel28, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jLabel27, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(txtOldName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtAbbrewCN, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .add(txtAbbrewPY, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(cbxRegionID, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cbxCustGrade, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(txtCustCode)
                        .add(cbxTradeclsid, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(txtNameCN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel12)
                            .add(jLabel25, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(jLabel29, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel31, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(txtNo)
                    .add(txtCustAddr, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .add(cbxCustLevel, 0, 258, Short.MAX_VALUE)
                    .add(txtFileNo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .add(cbxParentName, 0, 258, Short.MAX_VALUE)
                    .add(txtRemark, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .add(txtCounts, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtBank))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel23)
                            .add(jLabel2)
                            .add(txtNameCN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel3)
                                .add(jLabel1))
                            .add(cbxTradeclsid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(txtCustCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel13))))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(txtCustAddr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(cbxCustLevel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtFileNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(cbxCustGrade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel14)
                            .add(jLabel25)
                            .add(cbxRegionID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel24))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel26)
                            .add(txtAbbrewPY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtAbbrewCN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel27)
                            .add(jLabel32))
                        .add(9, 9, 9)
                        .add(jLabel28))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(cbxParentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtRemark, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel29)
                            .add(txtCounts, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel30)
                            .add(txtBank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel31)
                            .add(txtOldName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("\u8054\u7cfb\u4eba\u4fe1\u606f"));
        jLabel15.setText("\u8054\u7cfb\u4eba:");

        jLabel16.setText("\u8054\u7cfb\u4eba\u7535 \u8bdd:");

        jLabel17.setText("\u8054\u7cfb\u4eba\u79fb\u52a8\u7535\u8bdd:");

        jLabel18.setText("\u8054\u7cfb\u4eba\u7535\u5b50\u90ae\u4ef6:");

        jLabel19.setText("\u8054\u7cfb\u4eba\u4f20\u771f:");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .add(jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtLinkEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .add(txtLinkName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .add(txtLinkPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtLinkMobile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtLinkFax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtLinkName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtLinkPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(txtLinkMobile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(txtLinkEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtLinkFax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(130, 130, 130))
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ffcs/customerinfomgr/image/Save.png")));
        btnOK.setText("\u4fdd\u5b58");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ffcs/customerinfomgr/image/Cancel.png")));
        btnCancel.setText("\u53d6\u6d88");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ffcs/customerinfomgr/image/HLP.PNG")));
        jButton1.setText("\u5e2e\u52a9");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 495, Short.MAX_VALUE)
                .add(btnOK)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnCancel)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCancel)
                    .add(btnOK)
                    .add(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("\u5ba2\u6237\u7ecf\u7406\u4fe1\u606f"));
        jLabel20.setText("\u5ba2\u6237\u7ecf\u7406:");

        jLabel21.setText("\u5ba2\u6237\u7ecf\u7406\u79fb\u52a8\u7535\u8bdd:");

        jLabel22.setText("\u5ba2\u6237\u7ecf\u7406\u7535\u8bdd:");

        jPanel8.setLayout(null);

        jLabel4.setText("\u5ba2\u6237\u82f1\u6587\u540d\u79f0:");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(10, 10, 0, 15);

        jPanel8.add(txtNameEN);
        txtNameEN.setBounds(40, 10, 0, 20);

        jLabel11.setText("\u5ba2\u6237\u4fe1\u8a89\u7b49\u7ea7:");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(50, 10, 0, 15);

        cbxCreditLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(cbxCreditLevel);
        cbxCreditLevel.setBounds(190, 31, 61, 0);

        jLabel9.setText("\u5ba2\u6237\u7c7b\u578b:");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(10, 6, 27, 0);

        cbxCustType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(cbxCustType);
        cbxCustType.setBounds(40, 10, 0, 23);

        jLabel10.setText("\u670d\u52a1\u7b49\u7ea7:");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(10, 20, 0, 15);

        cbxServiceLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(cbxServiceLevel);
        cbxServiceLevel.setBounds(220, 61, 61, 0);

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel21, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel22, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtMgrPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .add(txtMgrName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtMgrMobile, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtMgrName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtMgrPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel22))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel21)
                    .add(txtMgrMobile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 750, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(9, 9, 9)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked
    
    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        //TODO add your handling code here:
        //if(check() ==  false){
        //     return;
        // }
        int selectIndex=0;
        if(txtNameCN.getText().length()<=0){
            JOptionPane.showMessageDialog(mainFrame,NbBundle.getMessage(getClass(),"customerIsMust"),
                    NbBundle.getMessage(getClass(),"message.notice"),JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if(!CheckStringUtil.cheakNumber(customerid)){
            JOptionPane.showMessageDialog(mainFrame,NbBundle.getMessage(getClass(),"customeridIsMust"),
                    NbBundle.getMessage(getClass(),"message.notice"),JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        selectIndex=cbxTradeclsid.getSelectedIndex();
        if(selectIndex==-1||cbxTradeclsid.getModel().getSelectedItem().toString().trim().length()<=0){
            JOptionPane.showMessageDialog(null,NbBundle.getMessage(getClass(),"mustSeletcTradecls"));
            return;
        }
        String id=cbxTradeclsid.getModel().getSelectedItem().toString();
        id=commandTradeId.getIdString(id);
        if(!CheckStringUtil.cheakNumber(id)){
            JOptionPane.showMessageDialog(mainFrame,NbBundle.getMessage(getClass(),"mustSelectTradeclsId"),
                    NbBundle.getMessage(getClass(),"message.notice"),JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        
        selectIndex=cbxRegionID.getSelectedIndex();
        if(selectIndex==-1||cbxRegionID.getModel().getSelectedItem().toString().trim().length()<=0){
            JOptionPane.showMessageDialog(null,NbBundle.getMessage(getClass(),"mustSelectRegion"));
            return;
        }
        String regionId=cbxRegionID.getModel().getSelectedItem().toString();
        regionId=commandRegionId.getIdString(regionId);
        if(!CheckStringUtil.cheakNumber(regionId)){
            JOptionPane.showMessageDialog(mainFrame,NbBundle.getMessage(getClass(),"mustSelectRegion"),
                    NbBundle.getMessage(getClass(),"message.notice"),JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        
        //获得bo
        ICustomerInfoMgrFacade mgr=(ICustomerInfoMgrFacade)AppContext.getInstance()
        .getAppContext().getBean("iCustomerInfoMgrFacade");
        
        
        Customer cust = new Customer();
        
        cust.setCustomerid(customerid);
        cust.setNamecn(txtNameCN.getText());
        cust.setTradeclsid(Integer.parseInt(commandTradeId.getIdString(cbxTradeclsid.getSelectedItem().toString())));
        cust.setNameen(txtNameEN.getText());
        cust.setCustcode(txtCustCode.getText());
        cust.setCustaddr(txtCustAddr.getText());
        cust.setCustgrade(Integer.parseInt(commandCbxCustGrade.getIdString(cbxCustGrade.getSelectedItem().toString())));
        cust.setCustlevel(Integer.parseInt(commandCbxCustLevel.getIdString(cbxCustLevel.getSelectedItem().toString())));
        cust.setCusttype(Integer.parseInt(commandCbxCustType.getIdString(cbxCustType.getSelectedItem().toString())));
        cust.setServicelevel(Integer.parseInt(commandCbxServiceLevel.getIdString(cbxServiceLevel.getSelectedItem().toString())));
        cust.setCreditlevel(Integer.parseInt(commandCbxCreditLevel.getIdString(cbxCreditLevel.getSelectedItem().toString())));
        cust.setLinkname(txtLinkName.getText());
        cust.setLinkphone(txtLinkPhone.getText());
        cust.setLinkmobile(txtLinkMobile.getText());
        cust.setLinkemail(txtLinkEmail.getText());
        cust.setLinkfax(txtLinkFax.getText());
        cust.setMngrname(txtMgrName.getText());
        cust.setMngrphone(txtMgrPhone.getText());
        cust.setMngrmobile(txtMgrMobile.getText());
        
        //new add file
        cust.setAbbrevCN(txtAbbrewCN.getText().trim());
        cust.setAbbrevPY(txtAbbrewPY.getText().trim());
        cust.setFileNO(txtFileNo.getText().trim());
        cust.setNo(txtNo.getText().trim());
        cust.setBank(txtBank.getText().trim());
        cust.setCounts(txtCounts.getText().trim());
        cust.setOldName(txtOldName.getText().trim());
        
        String parentcustomerid=null;
        if(cbxParentName.getSelectedItem()!=null){
            parentcustomerid=mgr.getCustomerIdByName(cbxParentName.getSelectedItem().toString());
        }
        
        cust.setParentcustomerid(parentcustomerid);
        
        
        cust.setRemark(txtRemark.getText());
        cust.setRegionid(Integer.parseInt(commandRegionId.getIdString(cbxRegionID.getSelectedItem().toString())));
        
        //上级用户为空时id为‘0’
        if(cust.getParentcustomerid() == null){
            cust.setParentcustomerid("0");
        }
        //上级用户不能是自己
        if(cust.getParentcustomerid().equals(cust.getCustomerid())){
            JOptionPane.showMessageDialog(WindowManager.getDefault().getMainWindow(),"上级用户不能是自己");
            return;
        }
        
        //判断是添加还是修改
        if(task.equals("add")){
            if(!mgr.isOnlyCustomerName(cust.getNamecn())){
                JOptionPane.showMessageDialog(mainFrame,NbBundle.getMessage(getClass(),"insure.rename"),
                        NbBundle.getMessage(getClass(),"message.notice"),JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int userid = Transform.StrToInt(System.getProperty("inms.userid","-1"));
            cust.setUserid(userid);
            mgr.addCustomerInfo(cust);
        }
        if(task.equals("change")){
            mgr.updateCustomerInfo(cust,cust.getCustomerid());
        }
        
        if(opener!=null){
            HashMap map=new HashMap();
            int userid = Transform.StrToInt(System.getProperty("inms.userid","-1"));
            map.put("userid",new Integer(userid));
            map.put("userid1",new Integer(userid));
            List list=mgr.getCustomerInfo(map);
            opener.validateTable(list);
        }
        this.dispose();
    }//GEN-LAST:event_btnOKMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInfoEditorJDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // 变量声明 - 不进行修改//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbxCreditLevel;
    private javax.swing.JComboBox cbxCustGrade;
    private javax.swing.JComboBox cbxCustLevel;
    private javax.swing.JComboBox cbxCustType;
    private javax.swing.JComboBox cbxParentName;
    private javax.swing.JComboBox cbxRegionID;
    private javax.swing.JComboBox cbxServiceLevel;
    private javax.swing.JComboBox cbxTradeclsid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtAbbrewCN;
    private javax.swing.JTextField txtAbbrewPY;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtCounts;
    private javax.swing.JTextField txtCustAddr;
    private javax.swing.JTextField txtCustCode;
    private javax.swing.JTextField txtFileNo;
    private javax.swing.JTextField txtLinkEmail;
    private javax.swing.JTextField txtLinkFax;
    private javax.swing.JTextField txtLinkMobile;
    private javax.swing.JTextField txtLinkName;
    private javax.swing.JTextField txtLinkPhone;
    private javax.swing.JTextField txtMgrMobile;
    private javax.swing.JTextField txtMgrName;
    private javax.swing.JTextField txtMgrPhone;
    private javax.swing.JTextField txtNameCN;
    private javax.swing.JTextField txtNameEN;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtOldName;
    private javax.swing.JTextField txtRemark;
    // 变量声明结束//GEN-END:variables
    private void chagneTitle(String task){
        if(task.equals("add")){
            this.setTitle(NbBundle.getMessage(getClass(),"title.add"));
        }
        if(task.equals("change")){
            this.setTitle(NbBundle.getMessage(getClass(),"title.change"));
        }
    }
    private void iniText(Customer customer){
        //初始化下拉列表框
        ITradeClsInfoMgrFacade mgrTradecls=(ITradeClsInfoMgrFacade)AppContext.getInstance()
        .getAppContext().getBean("iTradeClsInfoMgrImpl");
        List listId=mgrTradecls.getTradeClsId();
        List listName=mgrTradecls.getTradeClsNameCn();
        commandTradeId=new ComboxItemCommand(cbxTradeclsid,listId,listName);
        //初始化区域的下拉列表
        IRegionInfoMgrFacade mgrRegion=(IRegionInfoMgrFacade)AppContext.getInstance()
        .getAppContext().getBean("iRegionInfoMgrFacade");
        List regionlistId=mgrRegion.getRegionId();
        List regionlistName=mgrRegion.getRegionNameCn();
        commandRegionId=new ComboxItemCommand(cbxRegionID,regionlistId,regionlistName);
        //初始化客户等级，客户信誉等级，客户级别，服务等级，客户类型
        ICustomerInfoMgrFacade mgr=(ICustomerInfoMgrFacade)AppContext.getInstance()
        .getAppContext().getBean("iCustomerInfoMgrFacade");
        Codetbl codetbl=new Codetbl();
        codetbl.setTablename("CUSTOMERTBL");
        
        codetbl.setColname("CUSTGRADE");
        List custGradeValuecn=mgr.getCodetblRemark(codetbl);
        List custGradeId=mgr.getCodetblRemarkValue(codetbl);
        commandCbxCustGrade=new ComboxItemCommand(cbxCustGrade,custGradeId,custGradeValuecn);
        
        codetbl.setColname("CUSTLEVEL");
        List custTypeValuecn=mgr.getCodetblRemark(codetbl);
        List custTypeId=mgr.getCodetblRemarkValue(codetbl);
        commandCbxCustType=new ComboxItemCommand(cbxCustType,custTypeId,custTypeValuecn);
        
        codetbl.setColname("CREDITLEVEL");
        List custCreditLevelValuecn=mgr.getCodetblRemark(codetbl);
        List custCreditLevelId=mgr.getCodetblRemarkValue(codetbl);
        commandCbxCreditLevel=new ComboxItemCommand(cbxCreditLevel,custCreditLevelId,custCreditLevelValuecn);
        
        codetbl.setColname("CUSTTYPE");
        List custCustLine=mgr.getCodetblRemark(codetbl);
        List custCustLineId=mgr.getCodetblRemarkValue(codetbl);
        commandCbxCustLevel=new ComboxItemCommand(cbxCustLevel,custCustLineId,custCustLine);
        
        codetbl.setColname("SERVICELEVEL");
        List custServerLevel=mgr.getCodetblRemark(codetbl);
        List custServerLevelId=mgr.getCodetblRemarkValue(codetbl);
        commandCbxServiceLevel=new ComboxItemCommand(cbxServiceLevel,custServerLevelId,custServerLevel);
        
        
        customerid=String.valueOf(customer.getCustomerid());
        txtNameCN.setText(customer.getNamecn());
        cbxTradeclsid.getModel().setSelectedItem(commandTradeId.getItemString(String.valueOf(customer.getTradeclsid())));
        txtNameEN.setText(customer.getNameen());
        txtCustCode.setText(customer.getCustcode());
        txtCustAddr.setText(customer.getCustaddr());
        cbxCustGrade.setSelectedItem(commandCbxCustGrade.getItemString(String.valueOf(customer.getCustgrade())));
        cbxCustLevel.setSelectedItem(commandCbxCustLevel.getItemString(String.valueOf(customer.getCustlevel())));
        cbxCustType.setSelectedItem(commandCbxCustType.getItemString(String.valueOf(customer.getCusttype())));
        cbxServiceLevel.setSelectedItem(commandCbxServiceLevel.getItemString(String.valueOf(customer.getServicelevel())));
        cbxCreditLevel.setSelectedItem(commandCbxCreditLevel.getItemString(String.valueOf(customer.getCreditlevel())));
        
        txtLinkName.setText(customer.getLinkname());
        txtLinkPhone.setText(customer.getLinkphone());
        txtLinkMobile.setText(customer.getLinkmobile());
        txtLinkEmail.setText(customer.getLinkemail());
        txtLinkFax.setText(customer.getLinkfax());
        txtMgrName.setText(customer.getMngrname());
        txtMgrPhone.setText(customer.getMngrphone());
        txtMgrMobile.setText(customer.getMngrmobile());
        cbxParentName.addItem(customer.getParentname());
        cbxParentName.setSelectedItem(customer.getParentname());
        txtRemark.setText(customer.getRemark());
        cbxRegionID.getModel().setSelectedItem(commandRegionId.getItemString(String.valueOf(customer.getRegionid())));
        
        //new field
        txtAbbrewCN.setText(customer.getAbbrevCN());
        txtAbbrewPY.setText(customer.getAbbrevPY());
        txtBank.setText(customer.getBank());
        txtCounts.setText(customer.getCounts());
        txtFileNo.setText(customer.getFileNO());
        txtNo.setText(customer.getNo());
        txtOldName.setText(customer.getOldName());
    }
    
    private boolean checkInput(){
        return true;
    }
    
    private void restrictInput() {
        RestrictText restrictText=null;
        restrictText =new RestrictText(txtCustAddr);
        restrictText.setMaxSize(200);
        restrictText=new RestrictText(txtNameCN);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtNameEN);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtCustCode);
        restrictText.setMaxSize(765);
        restrictText=new RestrictText(txtLinkEmail);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtLinkFax);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtLinkMobile);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtLinkName);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtLinkPhone);
        restrictText.setMaxSize(100);
        restrictText=new RestrictText(txtMgrName);
        restrictText.setMaxSize(50);
        restrictText=new RestrictText(txtMgrMobile);
        restrictText.setMaxSize(50);
        restrictText=new RestrictText(txtMgrPhone);
        restrictText.setMaxSize(50);
        restrictText=new RestrictText(txtRemark);
        restrictText.setMaxSize(300);
    }
    
    
}
